# Generated by Django 5.0.3 on 2026-05-19 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('denied', 'Denied'), ('onboarding', 'Onboarding'), ('active', 'Active Tenant')], default='submitted', max_length=20)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('age', models.PositiveIntegerField()),
                ('space_type', models.CharField(blank=True, max_length=50)),
                ('space_label', models.CharField(blank=True, max_length=50)),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rent_due_day', models.IntegerField(default=1)),
                ('lease_start_date', models.DateField(blank=True, null=True)),
                ('deposit_required', models.DecimalField(decimal_places=2, default=450.0, max_digits=10)),
                ('deposit_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('utility_monthly', models.DecimalField(decimal_places=2, default=66.0, max_digits=10)),
                ('utility_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_address', models.CharField(blank=True, max_length=255)),
                ('current_address_length', models.CharField(blank=True, max_length=100)),
                ('previous_address_1', models.CharField(blank=True, max_length=255)),
                ('previous_address_1_length', models.CharField(blank=True, max_length=100)),
                ('previous_address_2', models.CharField(blank=True, max_length=255)),
                ('previous_address_2_length', models.CharField(blank=True, max_length=100)),
                ('previous_address_3', models.CharField(blank=True, max_length=255)),
                ('previous_address_3_length', models.CharField(blank=True, max_length=100)),
                ('drivers_license_number', models.CharField(blank=True, max_length=100)),
                ('has_valid_odl', models.BooleanField(default=False)),
                ('oregon_id_number', models.CharField(blank=True, max_length=100)),
                ('id_upload', models.FileField(blank=True, null=True, upload_to='application_ids/')),
                ('income_source', models.CharField(blank=True, max_length=255)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('employer_name', models.CharField(blank=True, max_length=255)),
                ('employment_length', models.CharField(blank=True, max_length=100)),
                ('previous_evictions', models.TextField(blank=True)),
                ('in_recovery', models.BooleanField(default=False)),
                ('drug_of_choice', models.CharField(blank=True, max_length=255)),
                ('on_parole', models.BooleanField(default=False)),
                ('parole_officer_name', models.CharField(blank=True, max_length=255)),
                ('parole_officer_phone', models.CharField(blank=True, max_length=50)),
                ('felony_history', models.TextField(blank=True)),
                ('odoc_time_served', models.BooleanField(default=False)),
                ('reference_1_name', models.CharField(blank=True, max_length=255)),
                ('reference_1_phone', models.CharField(blank=True, max_length=50)),
                ('reference_1_relationship', models.CharField(blank=True, max_length=255)),
                ('reference_1_type', models.CharField(blank=True, max_length=100)),
                ('reference_2_name', models.CharField(blank=True, max_length=255)),
                ('reference_2_phone', models.CharField(blank=True, max_length=50)),
                ('reference_2_relationship', models.CharField(blank=True, max_length=255)),
                ('reference_2_type', models.CharField(blank=True, max_length=100)),
                ('housing_need', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('sobriety_acknowledgment', models.BooleanField(default=False)),
                ('unconditional_regard_acknowledgment', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housing_application', to=settings.AUTH_USER_MODEL)),
                ('onboarding_invite', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_application', to='accounts.invitecode')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
