import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='financial_uploads/')),
                ('name', models.CharField(default='Financial Upload', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='property_photos/')),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('unit_size', models.CharField(blank=True, max_length=100)),
                ('cable_ready', models.BooleanField(default=True)),
                ('available_date', models.DateField(blank=True, null=True)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('utilities_cost', models.CharField(blank=True, max_length=255)),
                ('availability_status', models.CharField(choices=[('available', 'Available Now'), ('waitlist', 'Waitlist Open'), ('full', 'Currently Full')], default='full', max_length=20)),
                ('availability_message', models.CharField(default='Join Waitlist for Availability', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('tenant', 'Tenant / Applicant'), ('landlord', 'Landlord / Property Manager'), ('assistant', 'Assistant'), ('admin', 'Platform Admin')], default='tenant', max_length=20)),
                ('invite_code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('comment', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.blogpost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(blank=True, default='Painted Lady', max_length=255)),
                ('sheet_name', models.CharField(max_length=255)),
                ('row_number', models.IntegerField(default=0)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('entry_type', models.CharField(choices=[('income', 'Income'), ('operating_expense', 'Operating Expense'), ('debt_service', 'Debt Service'), ('capital_expense', 'Capital Expense'), ('other', 'Other')], default='other', max_length=50)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='main.financialupload')),
            ],
            options={
                'ordering': ['year', 'month', 'entry_type', 'category'],
            },
        ),
        migrations.CreateModel(
            name='HousingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('age', models.PositiveIntegerField()),
                ('space_type', models.CharField(blank=True, max_length=50)),
                ('space_label', models.CharField(blank=True, max_length=50)),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rent_due_day', models.IntegerField(default=1)),
                ('deposit_required', models.DecimalField(decimal_places=2, default=450.0, max_digits=10)),
                ('deposit_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('utility_monthly', models.DecimalField(decimal_places=2, default=66.0, max_digits=10)),
                ('utility_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_address', models.CharField(blank=True, max_length=255)),
                ('current_address_length', models.CharField(blank=True, max_length=100)),
                ('previous_address_1', models.CharField(blank=True, max_length=255)),
                ('previous_address_1_length', models.CharField(blank=True, max_length=100)),
                ('previous_address_2', models.CharField(blank=True, max_length=255)),
                ('previous_address_2_length', models.CharField(blank=True, max_length=100)),
                ('previous_address_3', models.CharField(blank=True, max_length=255)),
                ('previous_address_3_length', models.CharField(blank=True, max_length=100)),
                ('drivers_license_number', models.CharField(blank=True, max_length=100)),
                ('has_valid_odl', models.BooleanField(default=False)),
                ('oregon_id_number', models.CharField(blank=True, max_length=100)),
                ('id_upload', models.FileField(blank=True, null=True, upload_to='application_ids/')),
                ('income_source', models.CharField(max_length=255)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employer_name', models.CharField(blank=True, max_length=255)),
                ('employment_length', models.CharField(blank=True, max_length=100)),
                ('previous_evictions', models.TextField(blank=True)),
                ('in_recovery', models.BooleanField(default=False)),
                ('drug_of_choice', models.CharField(blank=True, max_length=255)),
                ('on_parole', models.BooleanField(default=False)),
                ('parole_officer_name', models.CharField(blank=True, max_length=255)),
                ('parole_officer_phone', models.CharField(blank=True, max_length=50)),
                ('felony_history', models.TextField(blank=True)),
                ('odoc_time_served', models.BooleanField(default=False)),
                ('reference_1_name', models.CharField(blank=True, max_length=255)),
                ('reference_1_phone', models.CharField(blank=True, max_length=50)),
                ('reference_1_relationship', models.CharField(blank=True, max_length=255)),
                ('reference_1_type', models.CharField(blank=True, max_length=100)),
                ('reference_2_name', models.CharField(blank=True, max_length=255)),
                ('reference_2_phone', models.CharField(blank=True, max_length=50)),
                ('reference_2_relationship', models.CharField(blank=True, max_length=255)),
                ('reference_2_type', models.CharField(blank=True, max_length=100)),
                ('housing_need', models.TextField()),
                ('additional_notes', models.TextField(blank=True)),
                ('sobriety_acknowledgment', models.BooleanField(default=False)),
                ('unconditional_regard_acknowledgment', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_profile', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='main.property')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('lease', 'Lease Agreement'), ('application_pdf', 'Application PDF'), ('id', 'Identification'), ('onboarding', 'Onboarding Document'), ('other', 'Other')], default='other', max_length=50)),
                ('file', models.FileField(upload_to='applicant_documents/')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('uploaded', 'Uploaded'), ('needs_completion', 'Needs Completion'), ('needs_signature', 'Needs Signature'), ('completed', 'Completed'), ('locked', 'Locked Final'), ('needs_correction', 'Needs Correction')], default='uploaded', max_length=30)),
                ('needs_signature', models.BooleanField(default=False)),
                ('needs_initials', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('landlord_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.housingapplication')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('rent', 'Rent'), ('deposit', 'Deposit'), ('utility', 'Utilities'), ('late_fee', 'Late Fee'), ('other', 'Other')], default='rent', max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='main.housingapplication')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.property')),
            ],
        ),
        migrations.CreateModel(
            name='RentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_history', to='main.housingapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('maintenance', 'Maintenance Request'), ('complaint', 'Complaint'), ('general', 'General Message'), ('document', 'Document Question')], default='general', max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('closed', 'Closed')], default='submitted', max_length=30)),
                ('locked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident_messages', to='main.housingapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
