# Generated by Django 5.0.3 on 2026-05-19 01:41

from django.db import migrations, models


def add_lease_start_date_if_missing(apps, schema_editor):
    table_name = "main_housingapplication"

    with schema_editor.connection.cursor() as cursor:
        existing_columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor,
                table_name,
            )
        }

    if "lease_start_date" in existing_columns:
        return

    HousingApplication = apps.get_model("main", "HousingApplication")
    field = models.DateField(blank=True, null=True)
    field.set_attributes_from_name("lease_start_date")
    schema_editor.add_field(HousingApplication, field)


def remove_lease_start_date_if_present(apps, schema_editor):
    table_name = "main_housingapplication"

    with schema_editor.connection.cursor() as cursor:
        existing_columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor,
                table_name,
            )
        }

    if "lease_start_date" not in existing_columns:
        return

    HousingApplication = apps.get_model("main", "HousingApplication")
    field = models.DateField(blank=True, null=True)
    field.set_attributes_from_name("lease_start_date")
    schema_editor.remove_field(HousingApplication, field)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_create_signeddocument'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_lease_start_date_if_missing,
                    remove_lease_start_date_if_present,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='housingapplication',
                    name='lease_start_date',
                    field=models.DateField(blank=True, null=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='signeddocument',
            name='document_type',
            field=models.CharField(choices=[('lease', 'Resident Lease Agreement'), ('emergency_contact', 'Emergency Contact Form'), ('painted_lady_acknowledgment', 'Painted Lady Acknowledgment'), ('lead_disclosure', 'Lead Disclosure'), ('asbestos_disclosure', 'Asbestos Disclosure'), ('house_rules', 'House Rules'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
