# Generated by Django 5.0.3 on 2026-05-19 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_housingapplication_lease_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('stripe_card', 'Stripe Card'), ('stripe_cashapp', 'Stripe Cash App Pay'), ('bank_transfer', 'Bank Transfer'), ('cashapp', 'Cash App'), ('cash', 'Cash'), ('check', 'Check'), ('money_order', 'Money Order'), ('zelle', 'Zelle'), ('ach', 'ACH'), ('other', 'Other')], default='stripe_card', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
