# Generated by Django 5.0.3 on 2026-05-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_payment_notes_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingapplication',
            name='deposit_payment_plan',
            field=models.CharField(choices=[('paid_in_full', 'Paid in full at move-in'), ('ninety_day_plan', 'Three payments over 90 days')], default='paid_in_full', max_length=30),
        ),
        migrations.AddField(
            model_name='signeddocument',
            name='deposit_payment_plan',
            field=models.CharField(choices=[('paid_in_full', 'Paid in full at move-in'), ('ninety_day_plan', 'Three payments over 90 days')], default='paid_in_full', max_length=30),
        ),
        migrations.AddField(
            model_name='signeddocument',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='signeddocument',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='signeddocument',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='signeddocument',
            name='emergency_medical_notes',
            field=models.TextField(blank=True),
        ),
    ]
