# Generated by Django 5.0.3 on 2026-05-19 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_housingapplication_deposit_payment_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='main.property'),
        ),
        migrations.AddField(
            model_name='housingapplication',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='resident_profile_photos/'),
        ),
    ]
