# Generated by Django 5.0.3 on 2026-05-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_blogpost_author_blogpost_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invite_code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='invite_code_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
