# Generated by Django 5.0.3 on 2026-05-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_user_invite_code_created_at_user_invite_code_used_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyOwnerIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('property_count', models.PositiveIntegerField(default=1)),
                ('total_units', models.PositiveIntegerField(default=0)),
                ('property_types', models.CharField(blank=True, max_length=255)),
                ('current_software', models.CharField(blank=True, max_length=255)),
                ('current_pain_points', models.TextField(blank=True)),
                ('migration_notes', models.TextField(blank=True)),
                ('needs_rent_collection', models.BooleanField(default=False)),
                ('needs_accounting', models.BooleanField(default=False)),
                ('needs_owner_reporting', models.BooleanField(default=False)),
                ('needs_data_migration', models.BooleanField(default=False)),
                ('needs_resident_files', models.BooleanField(default=False)),
                ('needs_documents', models.BooleanField(default=False)),
                ('needs_maintenance', models.BooleanField(default=False)),
                ('needs_resident_communication', models.BooleanField(default=False)),
                ('needs_screening', models.BooleanField(default=False)),
                ('needs_property_websites', models.BooleanField(default=False)),
                ('onboarding_timeline', models.CharField(blank=True, max_length=255)),
                ('dashboard_goals', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('tenant', 'Tenant / Applicant'), ('property_owner', 'Property Owner'), ('landlord', 'Landlord / Property Manager'), ('assistant', 'Assistant'), ('admin', 'Platform Admin')], default='tenant', max_length=20),
        ),
    ]
