# Generated by Django 5.0.3 on 2026-05-21 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_propertyownerintake_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyownerintake',
            name='invite_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyownerintake',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('invited', 'Invite Sent'), ('registered', 'Registered')], default='submitted', max_length=30),
        ),
        migrations.AddField(
            model_name='propertyownerintake',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_owner_intakes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LandlordIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('property_count', models.PositiveIntegerField(default=1)),
                ('total_units', models.PositiveIntegerField(default=0)),
                ('properties_managed', models.TextField(blank=True)),
                ('current_software', models.CharField(blank=True, max_length=255)),
                ('current_pain_points', models.TextField(blank=True)),
                ('migration_notes', models.TextField(blank=True)),
                ('needs_rent_collection', models.BooleanField(default=False)),
                ('needs_applications', models.BooleanField(default=False)),
                ('needs_resident_files', models.BooleanField(default=False)),
                ('needs_documents', models.BooleanField(default=False)),
                ('needs_maintenance', models.BooleanField(default=False)),
                ('needs_resident_communication', models.BooleanField(default=False)),
                ('needs_screening', models.BooleanField(default=False)),
                ('needs_accounting_access', models.BooleanField(default=False)),
                ('dashboard_goals', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('invited', 'Invite Sent'), ('registered', 'Registered')], default='submitted', max_length=30)),
                ('invite_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landlord_intakes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
