# Generated by Django 5.0.3 on 2026-05-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_propertyownerintake_invite_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landlordintake',
            options={'ordering': ['-created_at'], 'verbose_name': 'Landlord Invite / Profile', 'verbose_name_plural': 'Landlord Invites / Profiles'},
        ),
        migrations.AddField(
            model_name='landlordintake',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='landlordintake',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='landlordintake',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
