# Generated by Django 5.0.3 on 2026-05-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_property_created_at_existingresidentintake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdocument',
            name='document_type',
            field=models.CharField(choices=[('lease', 'Lease Agreement'), ('application_pdf', 'Application PDF'), ('id', 'Identification'), ('income', 'Proof of Income'), ('bank', 'Bank Statement / Deposit Verification'), ('onboarding', 'Onboarding Document'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
