# Generated by Django 5.0.3 on 2026-05-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_applicantdocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='landlord_email',
            field=models.EmailField(blank=True, help_text='Login email for the landlord or property manager assigned to this property.', max_length=254),
        ),
    ]
