# Generated by Django 5.0.3 on 2026-05-22 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_property_landlord_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialupload',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_uploads', to='main.property'),
        ),
    ]
