# Generated by Django 5.0.3 on 2026-05-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_financialupload_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='lease_type',
            field=models.CharField(choices=[('month_to_month', 'Month to Month'), ('lease', 'Lease')], default='month_to_month', max_length=30),
        ),
        migrations.AddField(
            model_name='property',
            name='rent_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
