# Generated by Django 5.0.3 on 2026-05-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_property_lease_type_property_rent_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='lease_type',
            field=models.CharField(blank=True, choices=[('month_to_month', 'Month to Month'), ('lease', 'Lease')], default='month_to_month', max_length=30),
        ),
    ]
