# Generated by Django 5.0.3 on 2026-05-22 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_property_lease_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='move_in_cost_notes',
            field=models.CharField(blank=True, help_text='Use for other move-in cost formulas or instructions.', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='move_in_cost_type',
            field=models.CharField(blank=True, choices=[('rent_deposit', 'Rent + Deposit'), ('first_last_deposit', 'First Month + Last Month + Deposit'), ('other', 'Other')], default='rent_deposit', max_length=30),
        ),
        migrations.CreateModel(
            name='PropertyOnboardingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('application', 'Rental Application'), ('lease', 'Lease Agreement'), ('other', 'Other Onboarding Document')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('source_file', models.FileField(upload_to='property_onboarding_documents/')),
                ('conversion_status', models.CharField(choices=[('uploaded', 'Uploaded for conversion'), ('mapped', 'Fillable mapping ready')], default='uploaded', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_documents', to='main.property')),
            ],
            options={
                'ordering': ['document_type', '-created_at'],
            },
        ),
    ]
