# Generated by Django 5.0.3 on 2026-05-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_property_move_in_cost_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyownerintake',
            name='advertises_available_units',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertyownerintake',
            name='charges_application_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertyownerintake',
            name='needs_custom_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertyownerintake',
            name='offers_renters_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertyownerintake',
            name='performs_background_checks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertyownerintake',
            name='uses_automatic_late_fees',
            field=models.BooleanField(default=False),
        ),
    ]
