# Generated by Django 5.0.3 on 2026-05-23 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_propertyownerintake_advertises_available_units_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('entry_type', models.CharField(choices=[('operating_expense', 'Operating Expense'), ('debt_service', 'Debt Service'), ('capital_expense', 'Capital Expense'), ('other', 'Other')], default='operating_expense', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expense_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Expense categories',
                'ordering': ['entry_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccountingReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_file', models.FileField(upload_to='accounting_receipts/')),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('entry_type', models.CharField(choices=[('operating_expense', 'Operating Expense'), ('debt_service', 'Debt Service'), ('capital_expense', 'Capital Expense'), ('other', 'Other')], default='operating_expense', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_method', models.CharField(choices=[('stripe_card', 'Stripe Card'), ('stripe_cashapp', 'Stripe Cash App Pay'), ('bank_transfer', 'Bank Transfer'), ('cashapp', 'Cash App'), ('cash', 'Cash'), ('check', 'Check'), ('money_order', 'Money Order'), ('zelle', 'Zelle'), ('ach', 'ACH'), ('other', 'Other')], default='other', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('needs_review', 'Needs Review'), ('approved', 'Approved'), ('ignored', 'Ignored / Duplicate')], default='needs_review', max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('financial_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_receipt', to='main.financialentry')),
                ('financial_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_sources', to='main.financialupload')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_receipts', to='main.property')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_accounting_receipts', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_accounting_receipts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='main.expensecategory')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
