# Generated by Django 5.0.3 on 2026-05-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_expensecategory_accountingreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='existingresidentintake',
            name='room_unit_label',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
