# Generated by Django 5.0.3 on 2026-05-23 17:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_existingresidentintake_room_unit_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingapplication',
            name='application_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='housingapplication',
            name='application_fee_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='housingapplication',
            name='background_check_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='housingapplication',
            name='background_check_fee_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='housingapplication',
            name='background_check_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housingapplication',
            name='background_check_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('ordered', 'Ordered'), ('cleared', 'Cleared'), ('needs_review', 'Needs Review'), ('declined', 'Declined'), ('waived', 'Waived')], default='not_required', max_length=30),
        ),
        migrations.AddField(
            model_name='property',
            name='application_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='application_fee_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='background_check_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='background_check_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='charges_application_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='renters_insurance_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='renters_insurance_provider_name',
            field=models.CharField(blank=True, default='Progressive Renters Insurance', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='renters_insurance_url',
            field=models.URLField(blank=True, default='https://www.progressive.com/renters/'),
        ),
        migrations.AddField(
            model_name='property',
            name='requires_background_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('deposit', 'Deposit'), ('utility', 'Utilities'), ('application_fee', 'Application Fee'), ('background_check_fee', 'Background Check Fee'), ('late_fee', 'Late Fee'), ('other', 'Other')], default='rent', max_length=30),
        ),
    ]
