# Generated by Django 5.0.3 on 2026-05-23 17:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_housingapplication_application_fee_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='application_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='background_check_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
