# Generated by Django 5.0.3 on 2026-05-24 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_property_application_fee_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentResidentRosterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('room_unit_label', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_resident_roster_entries', to='main.property')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_current_resident_roster_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['property__name', 'room_unit_label', 'last_name', 'first_name'],
                'unique_together': {('property', 'first_name', 'last_name', 'email', 'room_unit_label')},
            },
        ),
    ]
