# Generated by Django 5.0.3 on 2026-05-24 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_residentmessagereply'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingapplication',
            name='communication_preference',
            field=models.CharField(choices=[('portal', 'Portal Only'), ('sms', 'SMS Text'), ('email', 'Email')], default='portal', max_length=20),
        ),
        migrations.AddField(
            model_name='housingapplication',
            name='sms_opted_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housingapplication',
            name='sms_opted_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housingapplication',
            name='sms_opted_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housingapplication',
            name='sms_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SmsMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_phone', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('not_configured', 'Provider Not Configured'), ('skipped_no_consent', 'Skipped - No Consent'), ('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=30)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='main.housingapplication')),
                ('resident_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='main.residentmessage')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_sms_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
