# Generated by Django 5.0.3 on 2026-05-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_housingapplication_communication_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='existingresidentintake',
            name='sms_opted_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='existingresidentintake',
            name='sms_opted_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
