# Generated by Django 5.0.3 on 2026-05-24 07:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_existingresidentintake_sms_opted_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyRoomRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_unit_label', models.CharField(max_length=50)),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('rent_due_day', models.PositiveSmallIntegerField(default=1)),
                ('utility_monthly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_rents', to='main.property')),
            ],
            options={
                'ordering': ['property__name', 'room_unit_label'],
                'unique_together': {('property', 'room_unit_label')},
            },
        ),
    ]
