# Generated by Django 5.0.3 on 2026-05-24 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_propertyroomrent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMailboxConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailbox_email', models.EmailField(max_length=254, unique=True)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_company_mailboxes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['mailbox_email'],
            },
        ),
    ]
