# Generated by Django 5.0.3 on 2026-05-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_companymailboxconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialentry',
            name='ledger_scope',
            field=models.CharField(choices=[('property', 'Property Ledger'), ('company', 'Company Ledger'), ('bank', 'Bank Activity')], default='property', max_length=30),
        ),
        migrations.AddField(
            model_name='financialupload',
            name='ledger_scope',
            field=models.CharField(choices=[('property', 'Property Ledger'), ('company', 'Company Ledger'), ('bank', 'Bank Activity')], default='property', max_length=30),
        ),
    ]
