# Generated by Django 5.0.3 on 2026-05-25 02:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_financialentry_ledger_scope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyroomrent',
            name='deposit_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='propertyroomrent',
            name='deposit_required',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
